-- Generated schedule plans and tasks from HTML reference files

INSERT INTO schedule_plans (id, species, name, emoji, intro_title, intro_description, tips_title, tips_body, min_age_days, max_age_days) VALUES
  ('dog_newborn', 'dog', 'Newborn (0–8 weeks)', '🐣', 'Newborn (0–8 weeks)', 'This stage is entirely mom-led. Puppies are blind, deaf, and fully dependent. Your role is monitoring health, weight, and warmth — not scheduling. They nurse every 2 hours around the clock.', '🐣 Key Notes', 'If mom is present, let her do the work — your job is observation. Call your vet immediately if any pup is losing weight, crying constantly, rejected by mom, or feels cold to the touch. The socialization window (weeks 3–12) is the most critical period for a dog''s entire life — exposure now shapes temperament forever.', 0, 56),
  ('dog_young_puppy', 'dog', 'Young Puppy (8–12 weeks)', '🍼', 'Young Puppy (8–12 weeks)', 'The classic "new puppy" stage. Awake windows are only 1–1.5 hrs. Expect overnight potty trips, 3 meals/day, and lots of crate naps.', '🍼 Key Notes', 'Potty outside within 5–10 min of every meal, nap, and play session. Training sessions = 5 min max. Overnight trips should be boring on purpose — lights low, no talking. She''ll drop the overnight trip around 4–5 months.', 56, 84),
  ('dog_3_4_months', 'dog', '3–4 Months', '🌱', '3–4 Months', 'Awake windows stretch to ~2 hrs. Drop to 2 naps per day. Overnight potty trips become less frequent and may disappear entirely by month 4.', '🌱 Key Notes', 'Start leash manners now — short, positive walks. Increase training complexity: down, stay, leave it, loose leash. Socialization window is closing — prioritize new people, dogs, and environments. Potty intervals can stretch to every 2–3 hrs during the day.', 84, 120),
  ('dog_4_6_months', 'dog', '4–6 Months', '🐕', '4–6 Months', 'Most pups sleep through the night now. Awake windows hit 3 hrs. You can stay at 3 meals/day or begin transitioning to 2 — check with your vet.', '🐕 Key Notes', 'Overnight potty trips should be fully gone by now — celebrate! Adolescence begins around 5–6 months; expect some stubbornness and testing of boundaries. Stay consistent. Start working on recall, stay, and leave it in more distracting environments. Keep potty intervals to every 3 hrs max during the day.', 120, 180),
  ('dog_6_12_months', 'dog', '6–12 Months', '🦮', '6–12 Months', 'Two meals/day. More physical exercise needed. Adolescence peaks around 6–9 months — training consistency matters more than ever. Crate becomes optional for settled dogs.', '🦮 Key Notes', 'Adolescence is the hardest stretch — your pup may seem to "forget" training. Stay consistent and patient. Focus on real-world skills: greeting strangers politely, ignoring distractions on walks, staying calm at doors. Physical exercise + mental enrichment = a calmer dog. Potty intervals can now stretch to 4 hrs.', 180, 365),
  ('dog_adult', 'dog', 'Adult (1–7 years)', '🐶', 'Adult (1–7 years)', 'Two meals/day, 2–3 walks/day, no forced nap schedule. Bladder holds 4–6 hours comfortably. Training shifts to maintenance and fun activities.', '🐶 Key Notes', 'Exercise needs vary hugely by breed — a Border Collie needs 2 hrs/day, a Basset Hound is happy with 30 min. Mental enrichment (sniff walks, training, puzzle toys) is just as tiring as physical exercise. Annual vet checkups are key at this stage. Keep training skills fresh with occasional refreshers.', 365, 2555),
  ('dog_senior', 'dog', 'Senior (7+ years)', '🦳', 'Senior (7+ years)', 'Large breeds hit senior status around 6–7; small breeds around 10+. Shorter, gentler exercise. May need a midday potty trip back. Watch for joint stiffness, appetite changes, and cognitive signs.', '🦳 Key Notes', 'Bi-annual vet visits are recommended for seniors (every 6 months). Watch for: increased drinking/urinating, appetite loss, confusion at night, difficulty rising, or incontinence. Joint supplements (fish oil, glucosamine) may help — ask your vet. Keep their brain active with easy nose work and gentle training. Love them loudly — they''ve earned it. 🐾', 2555, NULL),
  ('cat_newborn', 'cat', 'Newborn (0–4 weeks)', '🐣', 'Newborn (0–4 weeks)', 'Entirely mom-dependent. Kittens are blind, deaf, and cannot regulate their own body temperature or eliminate without stimulation. Your role is monitoring — not scheduling.', '🐣 Key Notes', 'Fading Kitten Syndrome can strike fast — call your vet immediately if any kitten is cold, unresponsive, crying constantly, or not gaining weight. The socialization window is 2–9 weeks: the most important period in a cat''s life for human bonding. Gentle handling now = a friendlier cat forever.', 0, 28),
  ('cat_kitten', 'cat', 'Young Kitten (4–12 weeks)', '🍼', 'Young Kitten (4–12 weeks)', 'Weaning completes around 8 weeks. Kittens eat 4× a day, sleep in bursts, and enter their peak socialization window. Play is essential — it''s how they learn to be cats.', '🍼 Key Notes', 'Litter box: one box per cat plus one extra. Kittens figure it out quickly — place them in the box after every meal. Use unscented clumping litter. Never punish litter box misses — just clean and redirect. First vet visit should happen at 8 weeks for vaccines, deworming, and a health check.', 28, 84),
  ('cat_junior', 'cat', 'Junior (3–6 months)', '🌱', 'Junior (3–6 months)', 'Dropping to 3 meals/day. Growing fast — needs calorie-dense food. Zoomies are real. Spay/neuter window begins around 4–5 months. Personality is crystallizing.', '🌱 Key Notes', 'Spay/neuter is typically recommended around 4–5 months — before first heat in females. This dramatically reduces health risks and behavioral issues. Teething happens 3–6 months; redirect biting to toys, never hands. Start nail trims now — weekly touch of paws builds tolerance.', 84, 180),
  ('cat_adolescent', 'cat', 'Adolescent (6–18 months)', '🐈', 'Adolescent (6–18 months)', 'The "teenager" phase. High energy, boundary-testing, and peak nighttime activity. Two meals/day. Fully switched to adult food by 12 months. May become more territorial.', '🐈 Key Notes', 'The bedtime play session is the single most effective tool for reducing nighttime disruption — don''t skip it. If introducing a second cat, do it slowly: separate rooms, scent swapping first, then visual contact. Litter box hygiene becomes more important as territory instincts sharpen — scoop daily.', 180, 365),
  ('cat_adult', 'cat', 'Adult (1–7 years)', '🐱', 'Adult (1–7 years)', 'Two meals/day, consistent routine, and daily interactive play. This is the longest phase — the goal is enrichment, bonding, and prevention. Annual vet checkups are essential.', '🐱 Key Notes', 'Cats are obligate carnivores — quality of food matters enormously. Wet food is strongly preferred over dry for hydration and kidney health. Annual vet checkups catch issues early; dental disease is the most common and preventable problem. Keep the litter box scrupulously clean — cats will find creative alternatives if they dislike it.', 365, 2555),
  ('cat_mature', 'cat', 'Mature (7–11 years)', '🦳', 'Mature (7–11 years)', 'Often called the "middle-aged" cat. May start slowing down but is still very healthy. Bi-annual vet visits begin. Watch for weight changes, thirst, and litter box habits — these are the early warning signals.', '🦳 Key Notes', 'Bi-annual vet visits are the standard of care from here on. Blood panel once a year helps catch hyperthyroidism, kidney disease, and diabetes early — all common in cats this age. Weight loss despite good appetite is a red flag. Lower litter box sides if jumping becomes difficult. Keep routines as consistent as possible; mature cats are creatures of deep habit.', 2555, 4015),
  ('cat_senior', 'cat', 'Senior (11+ years)', '🌙', 'Senior / Elder (11+ years)', 'Cats at this age can live well into their late teens. Shorter, gentler everything — play, walks, grooming. Comfort, warmth, and familiarity matter most. Some cognitive decline is normal.', '🌙 Key Notes', 'Bi-annual vet visits with blood work are essential. Arthritis is very common and very treatable — watch for reluctance to jump, stiffness after rest, or missing the litter box. Provide ramps or steps to favorite spots. Keep food, water, and litter on the same floor. Nighttime yowling, disorientation, or staring into space may indicate feline cognitive dysfunction — talk to your vet. These years are precious. 🐾', 4015, NULL);

INSERT INTO schedule_tasks (id, plan_id, sort_order, time_label, category, title, subtitle, icon, section) VALUES
  ('dog_newborn_nurse_1', 'dog_newborn', 1, 'Every 2 hrs', 'feed', 'Nurse', 'Mom feeds; orphaned pups need bottle feeding every 2 hrs, including overnight', '🍼', 'Around the Clock (every 2 hrs)'),
  ('dog_newborn_sleep_2', 'dog_newborn', 2, 'Between feeds', 'sleep', 'Sleep', '90% of the day — normal and essential for brain development', '💤', 'Around the Clock (every 2 hrs)'),
  ('dog_newborn_weigh_each_pup_3', 'dog_newborn', 3, '2x daily', 'train', 'Weigh Each Pup', 'Should gain 10–15% of birth weight per day. Flag any not gaining.', '⚖️', 'Your Daily Tasks'),
  ('dog_newborn_gentle_handling_4', 'dog_newborn', 4, 'Daily', 'play', 'Gentle Handling', 'Brief handling from day 3 onward helps socialization. Keep warm.', '🤲', 'Your Daily Tasks'),
  ('dog_newborn_stimulate_elimination_5', 'dog_newborn', 5, 'After each feed', 'potty', 'Stimulate Elimination', 'If no mom: gently wipe belly/rear with warm damp cloth after every feeding', '🌿', 'Your Daily Tasks'),
  ('dog_newborn_monitor_temperature_6', 'dog_newborn', 6, 'Always on', 'wind', 'Monitor Temperature', 'Whelping box: 85–90°F week 1, reduce 5° each week. Pups can''t regulate body heat.', '🌡️', 'Your Daily Tasks'),
  ('dog_newborn_eyes_open_7', 'dog_newborn', 7, '~Day 10', 'sleep', 'Eyes Open', 'Vision is blurry at first — normal', '👀', 'Milestones to Watch'),
  ('dog_newborn_ears_open_8', 'dog_newborn', 8, '~Day 14', 'sleep', 'Ears Open', 'Start reacting to sounds', '👂', 'Milestones to Watch'),
  ('dog_newborn_begin_socialization_window_9', 'dog_newborn', 9, '~Week 3', 'play', 'Begin Socialization Window', 'Introduce gentle sounds, varied surfaces, human touch', '🐾', 'Milestones to Watch'),
  ('dog_newborn_begin_weaning_10', 'dog_newborn', 10, '~Week 4', 'feed', 'Begin Weaning', 'Introduce moistened puppy food; still nursing', '🍽️', 'Milestones to Watch'),
  ('dog_young_puppy_wake_up_potty_1', 'dog_young_puppy', 1, '5:30 AM', 'potty', 'Wake Up + Potty', 'Outside immediately — no delay', '🌿', 'Morning'),
  ('dog_young_puppy_meal_1_2', 'dog_young_puppy', 2, '5:40 AM', 'feed', 'Meal #1', 'Outside again within 10 min', '🍽️', 'Morning'),
  ('dog_young_puppy_short_play_3', 'dog_young_puppy', 3, '6:00 AM', 'play', 'Short Play', '5–10 min gentle play', '🧸', 'Morning'),
  ('dog_young_puppy_nap_in_crate_4', 'dog_young_puppy', 4, '6:30 AM', 'sleep', 'Nap in Crate', '~90 min', '💤', 'Morning'),
  ('dog_young_puppy_potty_break_5', 'dog_young_puppy', 5, '8:00 AM', 'potty', 'Potty Break', NULL, '🌿', 'Mid-Morning'),
  ('dog_young_puppy_training_6', 'dog_young_puppy', 6, '8:10 AM', 'train', 'Training', '5 min max — sit, name, recall', '⭐', 'Mid-Morning'),
  ('dog_young_puppy_explore_socialize_7', 'dog_young_puppy', 7, '8:20 AM', 'play', 'Explore / Socialize', 'Sounds, surfaces, gentle handling', '🧸', 'Mid-Morning'),
  ('dog_young_puppy_potty_break_8', 'dog_young_puppy', 8, '8:50 AM', 'potty', 'Potty Break', NULL, '🌿', 'Mid-Morning'),
  ('dog_young_puppy_nap_in_crate_9', 'dog_young_puppy', 9, '9:00 AM', 'sleep', 'Nap in Crate', '~90 min', '💤', 'Mid-Morning'),
  ('dog_young_puppy_potty_break_10', 'dog_young_puppy', 10, '10:30 AM', 'potty', 'Potty Break', NULL, '🌿', 'Midday'),
  ('dog_young_puppy_play_short_training_11', 'dog_young_puppy', 11, '10:40 AM', 'play', 'Play + Short Training', NULL, '🧸', 'Midday'),
  ('dog_young_puppy_potty_break_12', 'dog_young_puppy', 12, '11:30 AM', 'potty', 'Potty Break', NULL, '🌿', 'Midday'),
  ('dog_young_puppy_meal_2_13', 'dog_young_puppy', 13, '11:40 AM', 'feed', 'Meal #2', 'Outside again within 10 min', '🍽️', 'Midday'),
  ('dog_young_puppy_long_midday_nap_14', 'dog_young_puppy', 14, '12:00 PM', 'sleep', 'Long Midday Nap', '1.5–2 hrs in crate', '💤', 'Midday'),
  ('dog_young_puppy_potty_break_15', 'dog_young_puppy', 15, '1:30 PM', 'potty', 'Potty Break', NULL, '🌿', 'Afternoon'),
  ('dog_young_puppy_play_explore_16', 'dog_young_puppy', 16, '1:40 PM', 'play', 'Play + Explore', NULL, '🧸', 'Afternoon'),
  ('dog_young_puppy_training_17', 'dog_young_puppy', 17, '2:10 PM', 'train', 'Training', '5 min max', '⭐', 'Afternoon'),
  ('dog_young_puppy_nap_18', 'dog_young_puppy', 18, '2:30 PM', 'sleep', 'Nap', '~90 min', '💤', 'Afternoon'),
  ('dog_young_puppy_potty_break_19', 'dog_young_puppy', 19, '4:00 PM', 'potty', 'Potty Break', NULL, '🌿', 'Evening'),
  ('dog_young_puppy_meal_3_20', 'dog_young_puppy', 20, '5:30 PM', 'feed', 'Meal #3', 'Outside within 10 min after eating', '🍽️', 'Evening'),
  ('dog_young_puppy_active_play_21', 'dog_young_puppy', 21, '6:00 PM', 'play', 'Active Play', 'Most energetic window', '🧸', 'Evening'),
  ('dog_young_puppy_evening_nap_22', 'dog_young_puppy', 22, '6:30 PM', 'sleep', 'Evening Nap', '~60–90 min', '💤', 'Evening'),
  ('dog_young_puppy_wind_down_23', 'dog_young_puppy', 23, '8:00 PM', 'wind', 'Wind Down', 'Calm time, chew toy. Limit water after 8 PM.', '🕯️', 'Evening'),
  ('dog_young_puppy_last_potty_24', 'dog_young_puppy', 24, '9:15 PM', 'potty', 'Last Potty', NULL, '🌿', 'Evening'),
  ('dog_young_puppy_bedtime_in_crate_25', 'dog_young_puppy', 25, '9:30 PM', 'sleep', 'Bedtime in Crate', NULL, '🌙', 'Evening'),
  ('dog_young_puppy_overnight_potty_26', 'dog_young_puppy', 26, '~1:30 AM', 'night', 'Overnight Potty', 'Quiet & calm. No play. Straight back to crate.', '🌿', 'Overnight'),
  ('dog_3_4_months_wake_up_potty_1', 'dog_3_4_months', 1, '5:30 AM', 'potty', 'Wake Up + Potty', 'Outside immediately', '🌿', 'Morning'),
  ('dog_3_4_months_meal_1_2', 'dog_3_4_months', 2, '5:40 AM', 'feed', 'Meal #1', 'Outside again within 10 min', '🍽️', 'Morning'),
  ('dog_3_4_months_play_training_3', 'dog_3_4_months', 3, '6:00 AM', 'play', 'Play + Training', '10–15 min, more complex commands: down, stay, leave it', '🧸', 'Morning'),
  ('dog_3_4_months_potty_break_4', 'dog_3_4_months', 4, '7:30 AM', 'potty', 'Potty Break', NULL, '🌿', 'Morning'),
  ('dog_3_4_months_morning_nap_5', 'dog_3_4_months', 5, '8:00 AM', 'sleep', 'Morning Nap', '~1.5–2 hrs in crate', '💤', 'Morning'),
  ('dog_3_4_months_potty_break_6', 'dog_3_4_months', 6, '10:00 AM', 'potty', 'Potty Break', NULL, '🌿', 'Midday'),
  ('dog_3_4_months_explore_socialize_7', 'dog_3_4_months', 7, '10:10 AM', 'play', 'Explore + Socialize', 'Leash walks starting now — short and positive', '🧸', 'Midday'),
  ('dog_3_4_months_training_session_8', 'dog_3_4_months', 8, '11:00 AM', 'train', 'Training Session', '10 min max', '⭐', 'Midday'),
  ('dog_3_4_months_potty_break_9', 'dog_3_4_months', 9, '11:30 AM', 'potty', 'Potty Break', NULL, '🌿', 'Midday'),
  ('dog_3_4_months_meal_2_10', 'dog_3_4_months', 10, '11:40 AM', 'feed', 'Meal #2', 'Outside within 10 min', '🍽️', 'Midday'),
  ('dog_3_4_months_long_afternoon_nap_11', 'dog_3_4_months', 11, '12:00 PM', 'sleep', 'Long Afternoon Nap', '2–2.5 hrs', '💤', 'Midday'),
  ('dog_3_4_months_potty_break_12', 'dog_3_4_months', 12, '2:30 PM', 'potty', 'Potty Break', NULL, '🌿', 'Afternoon'),
  ('dog_3_4_months_active_play_13', 'dog_3_4_months', 13, '2:40 PM', 'play', 'Active Play', 'Fetch, tug, enrichment toys', '🧸', 'Afternoon'),
  ('dog_3_4_months_training_session_14', 'dog_3_4_months', 14, '3:30 PM', 'train', 'Training Session', '10 min max', '⭐', 'Afternoon'),
  ('dog_3_4_months_potty_break_15', 'dog_3_4_months', 15, '4:00 PM', 'potty', 'Potty Break', NULL, '🌿', 'Afternoon'),
  ('dog_3_4_months_meal_3_16', 'dog_3_4_months', 16, '5:30 PM', 'feed', 'Meal #3', 'Outside within 10 min', '🍽️', 'Evening'),
  ('dog_3_4_months_evening_play_17', 'dog_3_4_months', 17, '6:00 PM', 'play', 'Evening Play', NULL, '🧸', 'Evening'),
  ('dog_3_4_months_potty_break_18', 'dog_3_4_months', 18, '7:30 PM', 'potty', 'Potty Break', NULL, '🌿', 'Evening'),
  ('dog_3_4_months_wind_down_19', 'dog_3_4_months', 19, '8:30 PM', 'wind', 'Wind Down', 'Chew toy, calm time. Limit water after 8 PM.', '🕯️', 'Evening'),
  ('dog_3_4_months_last_potty_20', 'dog_3_4_months', 20, '9:15 PM', 'potty', 'Last Potty', NULL, '🌿', 'Evening'),
  ('dog_3_4_months_bedtime_21', 'dog_3_4_months', 21, '9:30 PM', 'sleep', 'Bedtime', NULL, '🌙', 'Evening'),
  ('dog_3_4_months_overnight_potty_if_needed_22', 'dog_3_4_months', 22, '~2:00 AM', 'night', 'Overnight Potty (if needed)', 'Many pups drop this by 4 months — celebrate when it''s gone!', '🌿', 'Overnight'),
  ('dog_4_6_months_wake_up_potty_1', 'dog_4_6_months', 1, '5:30 AM', 'potty', 'Wake Up + Potty', NULL, '🌿', 'Morning'),
  ('dog_4_6_months_meal_1_2', 'dog_4_6_months', 2, '5:45 AM', 'feed', 'Meal #1', 'Outside within 15 min', '🍽️', 'Morning'),
  ('dog_4_6_months_morning_walk_or_play_3', 'dog_4_6_months', 3, '6:15 AM', 'play', 'Morning Walk or Play', '15–20 min leash walk', '🧸', 'Morning'),
  ('dog_4_6_months_training_4', 'dog_4_6_months', 4, '7:00 AM', 'train', 'Training', '10–15 min — heel, place, impulse control', '⭐', 'Morning'),
  ('dog_4_6_months_morning_rest_5', 'dog_4_6_months', 5, '8:00 AM', 'sleep', 'Morning Rest', 'Crate or settle — ~1.5 hrs', '💤', 'Morning'),
  ('dog_4_6_months_potty_break_6', 'dog_4_6_months', 6, '10:00 AM', 'potty', 'Potty Break', NULL, '🌿', 'Midday'),
  ('dog_4_6_months_enrichment_play_7', 'dog_4_6_months', 7, '10:15 AM', 'play', 'Enrichment / Play', 'Puzzle toys, sniff walks, fetch', '🧸', 'Midday'),
  ('dog_4_6_months_meal_2_if_3x_day_8', 'dog_4_6_months', 8, '12:00 PM', 'feed', 'Meal #2 (if 3x/day)', 'Outside within 15 min', '🍽️', 'Midday'),
  ('dog_4_6_months_midday_nap_9', 'dog_4_6_months', 9, '12:30 PM', 'sleep', 'Midday Nap', '1.5–2 hrs', '💤', 'Midday'),
  ('dog_4_6_months_potty_break_10', 'dog_4_6_months', 10, '2:30 PM', 'potty', 'Potty Break', NULL, '🌿', 'Afternoon'),
  ('dog_4_6_months_active_play_11', 'dog_4_6_months', 11, '2:45 PM', 'play', 'Active Play', 'Higher energy — fetch, tug, off-leash if safe', '🧸', 'Afternoon'),
  ('dog_4_6_months_training_session_12', 'dog_4_6_months', 12, '3:30 PM', 'train', 'Training Session', '15 min max', '⭐', 'Afternoon'),
  ('dog_4_6_months_potty_break_13', 'dog_4_6_months', 13, '4:15 PM', 'potty', 'Potty Break', NULL, '🌿', 'Afternoon'),
  ('dog_4_6_months_meal_3_or_meal_2_if_2x_day_14', 'dog_4_6_months', 14, '5:30 PM', 'feed', 'Meal #3 (or Meal #2 if 2x/day)', 'Outside within 15 min', '🍽️', 'Evening'),
  ('dog_4_6_months_evening_walk_15', 'dog_4_6_months', 15, '6:00 PM', 'play', 'Evening Walk', '20–30 min', '🧸', 'Evening'),
  ('dog_4_6_months_potty_break_16', 'dog_4_6_months', 16, '8:00 PM', 'potty', 'Potty Break', NULL, '🌿', 'Evening'),
  ('dog_4_6_months_wind_down_17', 'dog_4_6_months', 17, '8:30 PM', 'wind', 'Wind Down', 'Chew toy, calm settle', '🕯️', 'Evening'),
  ('dog_4_6_months_last_potty_18', 'dog_4_6_months', 18, '9:15 PM', 'potty', 'Last Potty', NULL, '🌿', 'Evening'),
  ('dog_4_6_months_bedtime_sleeping_through_the_night_19', 'dog_4_6_months', 19, '9:30 PM', 'sleep', 'Bedtime — sleeping through the night 🎉', NULL, '🌙', 'Evening'),
  ('dog_6_12_months_wake_up_potty_1', 'dog_6_12_months', 1, '5:30 AM', 'potty', 'Wake Up + Potty', NULL, '🌿', 'Morning'),
  ('dog_6_12_months_meal_1_2', 'dog_6_12_months', 2, '5:45 AM', 'feed', 'Meal #1', 'Outside within 15 min', '🍽️', 'Morning'),
  ('dog_6_12_months_morning_walk_3', 'dog_6_12_months', 3, '6:15 AM', 'play', 'Morning Walk', '20–30 min — leash manners practice', '🧸', 'Morning'),
  ('dog_6_12_months_training_4', 'dog_6_12_months', 4, '7:00 AM', 'train', 'Training', '15 min — proofing commands in new environments', '⭐', 'Morning'),
  ('dog_6_12_months_potty_break_5', 'dog_6_12_months', 5, '11:00 AM', 'potty', 'Potty Break', NULL, '🌿', 'Midday'),
  ('dog_6_12_months_enrichment_6', 'dog_6_12_months', 6, '11:15 AM', 'play', 'Enrichment', 'Puzzle feeder, sniff walk, playtime with another dog', '🧸', 'Midday'),
  ('dog_6_12_months_rest_period_7', 'dog_6_12_months', 7, '12:00 PM', 'sleep', 'Rest Period', 'Dog should be able to settle independently', '💤', 'Midday'),
  ('dog_6_12_months_potty_break_8', 'dog_6_12_months', 8, '2:00 PM', 'potty', 'Potty Break', NULL, '🌿', 'Afternoon'),
  ('dog_6_12_months_active_exercise_9', 'dog_6_12_months', 9, '2:15 PM', 'play', 'Active Exercise', 'Fetch, running, off-leash park — burn that adolescent energy', '🧸', 'Afternoon'),
  ('dog_6_12_months_training_session_10', 'dog_6_12_months', 10, '3:30 PM', 'train', 'Training Session', '15 min — advanced skills, impulse control, distraction proofing', '⭐', 'Afternoon'),
  ('dog_6_12_months_potty_break_11', 'dog_6_12_months', 11, '4:00 PM', 'potty', 'Potty Break', NULL, '🌿', 'Afternoon'),
  ('dog_6_12_months_meal_2_12', 'dog_6_12_months', 12, '5:30 PM', 'feed', 'Meal #2', 'Outside within 15 min', '🍽️', 'Evening'),
  ('dog_6_12_months_evening_walk_13', 'dog_6_12_months', 13, '6:00 PM', 'play', 'Evening Walk', '30 min — sniff time matters for mental fatigue', '🧸', 'Evening'),
  ('dog_6_12_months_potty_break_14', 'dog_6_12_months', 14, '8:30 PM', 'potty', 'Potty Break', NULL, '🌿', 'Evening'),
  ('dog_6_12_months_wind_down_15', 'dog_6_12_months', 15, '9:00 PM', 'wind', 'Wind Down', 'Calm settle, chew toy or Kong', '🕯️', 'Evening'),
  ('dog_6_12_months_last_potty_16', 'dog_6_12_months', 16, '9:15 PM', 'potty', 'Last Potty', NULL, '🌿', 'Evening'),
  ('dog_6_12_months_bedtime_17', 'dog_6_12_months', 17, '9:30 PM', 'sleep', 'Bedtime', NULL, '🌙', 'Evening'),
  ('dog_adult_morning_potty_1', 'dog_adult', 1, '6:00 AM', 'potty', 'Morning Potty', NULL, '🌿', 'Morning'),
  ('dog_adult_meal_1_2', 'dog_adult', 2, '6:15 AM', 'feed', 'Meal #1', NULL, '🍽️', 'Morning'),
  ('dog_adult_morning_walk_exercise_3', 'dog_adult', 3, '6:45 AM', 'play', 'Morning Walk / Exercise', '30–60 min depending on breed energy level', '🧸', 'Morning'),
  ('dog_adult_midday_potty_4', 'dog_adult', 4, '12:00 PM', 'potty', 'Midday Potty', 'Can extend to every 4–6 hrs for well-trained adults', '🌿', 'Midday'),
  ('dog_adult_enrichment_optional_5', 'dog_adult', 5, '12:15 PM', 'play', 'Enrichment (optional)', 'Kong, puzzle toy, brief training refresher', '🧸', 'Midday'),
  ('dog_adult_afternoon_potty_6', 'dog_adult', 6, '4:00 PM', 'potty', 'Afternoon Potty', NULL, '🌿', 'Afternoon'),
  ('dog_adult_afternoon_activity_7', 'dog_adult', 7, '4:15 PM', 'play', 'Afternoon Activity', 'Walk, fetch, dog park, training games', '🧸', 'Afternoon'),
  ('dog_adult_meal_2_8', 'dog_adult', 8, '5:30 PM', 'feed', 'Meal #2', NULL, '🍽️', 'Evening'),
  ('dog_adult_evening_walk_9', 'dog_adult', 9, '6:00 PM', 'play', 'Evening Walk', '30–45 min', '🧸', 'Evening'),
  ('dog_adult_last_potty_10', 'dog_adult', 10, '9:00 PM', 'potty', 'Last Potty', NULL, '🌿', 'Evening'),
  ('dog_adult_bedtime_11', 'dog_adult', 11, '9:30 PM', 'sleep', 'Bedtime', 'Crate optional — many adults settle freely', '🌙', 'Evening'),
  ('dog_senior_morning_potty_1', 'dog_senior', 1, '6:00 AM', 'potty', 'Morning Potty', 'May be more urgent — get outside promptly', '🌿', 'Morning'),
  ('dog_senior_meal_1_2', 'dog_senior', 2, '6:15 AM', 'feed', 'Meal #1', 'Senior formula if vet recommends. Consider 3 smaller meals.', '🍽️', 'Morning'),
  ('dog_senior_gentle_morning_walk_3', 'dog_senior', 3, '6:45 AM', 'play', 'Gentle Morning Walk', '15–30 min, slow pace, let them sniff — sniffing is enrichment', '🧸', 'Morning'),
  ('dog_senior_rest_4', 'dog_senior', 4, '8:00 AM', 'sleep', 'Rest', 'Seniors sleep more — totally normal', '💤', 'Morning'),
  ('dog_senior_midday_potty_5', 'dog_senior', 5, '11:00 AM', 'potty', 'Midday Potty', 'Bladder control weakens — add this trip back in', '🌿', 'Midday'),
  ('dog_senior_meal_2_if_3x_day_6', 'dog_senior', 6, '12:00 PM', 'feed', 'Meal #2 (if 3x/day)', 'Smaller meals are easier on digestion', '🍽️', 'Midday'),
  ('dog_senior_gentle_enrichment_7', 'dog_senior', 7, '12:30 PM', 'play', 'Gentle Enrichment', 'Sniff walk, easy puzzle toy, light play', '🧸', 'Midday'),
  ('dog_senior_afternoon_rest_8', 'dog_senior', 8, '1:30 PM', 'sleep', 'Afternoon Rest', NULL, '💤', 'Midday'),
  ('dog_senior_potty_break_9', 'dog_senior', 9, '3:30 PM', 'potty', 'Potty Break', NULL, '🌿', 'Afternoon'),
  ('dog_senior_short_walk_or_play_10', 'dog_senior', 10, '3:45 PM', 'play', 'Short Walk or Play', 'Watch for limping, stiffness, or reluctance — ease off if needed', '🧸', 'Afternoon'),
  ('dog_senior_meal_2_or_3_11', 'dog_senior', 11, '5:30 PM', 'feed', 'Meal #2 or #3', NULL, '🍽️', 'Evening'),
  ('dog_senior_evening_stroll_12', 'dog_senior', 12, '6:00 PM', 'play', 'Evening Stroll', 'Gentle, unhurried — quality over quantity', '🧸', 'Evening'),
  ('dog_senior_potty_break_13', 'dog_senior', 13, '8:30 PM', 'potty', 'Potty Break', NULL, '🌿', 'Evening'),
  ('dog_senior_settle_14', 'dog_senior', 14, '9:00 PM', 'wind', 'Settle', 'Orthopedic bed is worth the investment at this stage', '🕯️', 'Evening'),
  ('dog_senior_last_potty_15', 'dog_senior', 15, '9:15 PM', 'potty', 'Last Potty', NULL, '🌿', 'Evening'),
  ('dog_senior_bedtime_16', 'dog_senior', 16, '9:30 PM', 'sleep', 'Bedtime', NULL, '🌙', 'Evening'),
  ('cat_newborn_nurse_1', 'cat_newborn', 1, 'Every 2 hrs', 'feed', 'Nurse', 'Mom feeds freely. Orphaned kittens need kitten milk replacer (KMR) every 2 hrs including overnight — never cow''s milk.', '🍼', 'Around the Clock'),
  ('cat_newborn_sleep_2', 'cat_newborn', 2, 'Between feeds', 'sleep', 'Sleep', 'Nearly 90% of the day — essential for brain and organ development', '💤', 'Around the Clock'),
  ('cat_newborn_stimulate_elimination_3', 'cat_newborn', 3, 'After each feed', 'groom', 'Stimulate Elimination', 'Gently wipe belly and rear with a warm damp cloth. Mom does this naturally; you must replicate if orphaned.', '🧻', 'Around the Clock'),
  ('cat_newborn_weigh_each_kitten_4', 'cat_newborn', 4, '2× daily', 'vet', 'Weigh Each Kitten', 'Should gain ~7–10g per day. Any weight loss = vet call.', '⚖️', 'Your Daily Tasks'),
  ('cat_newborn_monitor_warmth_5', 'cat_newborn', 5, 'Always on', 'note', 'Monitor Warmth', 'Nest: 85–90°F week 1, down to 75°F by week 4. Kittens cluster to stay warm.', '🌡️', 'Your Daily Tasks'),
  ('cat_newborn_gentle_daily_handling_6', 'cat_newborn', 6, 'From day 3', 'play', 'Gentle Daily Handling', 'Brief, calm contact from day 3 dramatically improves socialization outcomes', '🤲', 'Your Daily Tasks'),
  ('cat_newborn_eyes_open_7', 'cat_newborn', 7, '~Day 10', 'sleep', 'Eyes Open', 'Blue at first — all kittens are born with blue eyes', '👀', 'Milestones'),
  ('cat_newborn_ears_unfold_8', 'cat_newborn', 8, '~Day 14', 'sleep', 'Ears Unfold', 'Begin reacting to sound', '👂', 'Milestones'),
  ('cat_newborn_first_wobbly_steps_9', 'cat_newborn', 9, '~Week 3', 'play', 'First Wobbly Steps', 'Start introducing soft surfaces and smells', '🐾', 'Milestones'),
  ('cat_newborn_begin_weaning_10', 'cat_newborn', 10, '~Week 4', 'feed', 'Begin Weaning', 'Introduce wet kitten food mixed with KMR; still nursing', '🍽️', 'Milestones'),
  ('cat_kitten_meal_1_1', 'cat_kitten', 1, '6:00 AM', 'feed', 'Meal #1', 'Wet kitten food — high protein, no grain fillers. Small portions 4× daily.', '🍽️', 'Morning'),
  ('cat_kitten_morning_play_session_2', 'cat_kitten', 2, '6:20 AM', 'play', 'Morning Play Session', '5–10 min wand or feather toy — mimics hunt sequence', '🪄', 'Morning'),
  ('cat_kitten_nap_3', 'cat_kitten', 3, '7:00 AM', 'sleep', 'Nap', 'Kittens sleep 16–20 hrs/day in short bursts', '💤', 'Morning'),
  ('cat_kitten_meal_2_4', 'cat_kitten', 4, '11:00 AM', 'feed', 'Meal #2', NULL, '🍽️', 'Midday'),
  ('cat_kitten_play_explore_5', 'cat_kitten', 5, '11:20 AM', 'play', 'Play + Explore', 'Introduce new textures, sounds, people — socialization window is closing', '🪄', 'Midday'),
  ('cat_kitten_handling_practice_6', 'cat_kitten', 6, '11:50 AM', 'groom', 'Handling Practice', 'Touch paws, ears, mouth — builds tolerance for future grooming/vet visits', '🖐️', 'Midday'),
  ('cat_kitten_nap_7', 'cat_kitten', 7, '12:00 PM', 'sleep', 'Nap', NULL, '💤', 'Midday'),
  ('cat_kitten_meal_3_8', 'cat_kitten', 8, '3:00 PM', 'feed', 'Meal #3', NULL, '🍽️', 'Afternoon'),
  ('cat_kitten_play_session_9', 'cat_kitten', 9, '3:20 PM', 'play', 'Play Session', 'End each play session with a "catch" — let them grab the toy. Builds confidence.', '🪄', 'Afternoon'),
  ('cat_kitten_nap_10', 'cat_kitten', 10, '4:00 PM', 'sleep', 'Nap', NULL, '💤', 'Afternoon'),
  ('cat_kitten_meal_4_11', 'cat_kitten', 11, '7:00 PM', 'feed', 'Meal #4', NULL, '🍽️', 'Evening'),
  ('cat_kitten_active_evening_play_12', 'cat_kitten', 12, '7:20 PM', 'play', 'Active Evening Play', 'Peak activity time — lean into it with high-energy play to tire them out', '🪄', 'Evening'),
  ('cat_kitten_grooming_intro_13', 'cat_kitten', 13, '8:00 PM', 'groom', 'Grooming Intro', 'Soft brush, short session — make it positive with treats', '🪮', 'Evening'),
  ('cat_kitten_settle_for_night_14', 'cat_kitten', 14, '9:00 PM', 'sleep', 'Settle for Night', 'Kittens may still be active at night — this is normal', '🌙', 'Evening'),
  ('cat_junior_meal_1_1', 'cat_junior', 1, '7:00 AM', 'feed', 'Meal #1', '3× daily now — still kitten formula, high protein', '🍽️', 'Morning'),
  ('cat_junior_morning_play_2', 'cat_junior', 2, '7:20 AM', 'play', 'Morning Play', '10–15 min — they have more stamina now', '🪄', 'Morning'),
  ('cat_junior_rest_period_3', 'cat_junior', 3, '8:00 AM', 'sleep', 'Rest Period', NULL, '💤', 'Morning'),
  ('cat_junior_meal_2_4', 'cat_junior', 4, '12:00 PM', 'feed', 'Meal #2', NULL, '🍽️', 'Midday'),
  ('cat_junior_enrichment_5', 'cat_junior', 5, '12:20 PM', 'play', 'Enrichment', 'Puzzle feeders, crinkle balls, paper bags — encourage independent play', '🪄', 'Midday'),
  ('cat_junior_grooming_6', 'cat_junior', 6, '1:00 PM', 'groom', 'Grooming', 'Daily brushing habit starts now — much easier than introducing it to an adult', '🪮', 'Midday'),
  ('cat_junior_afternoon_rest_7', 'cat_junior', 7, '1:30 PM', 'sleep', 'Afternoon Rest', NULL, '💤', 'Midday'),
  ('cat_junior_active_play_8', 'cat_junior', 8, '5:00 PM', 'play', 'Active Play', '15–20 min wand toy — full hunt sequence: stalk, chase, pounce, catch, kill', '🪄', 'Evening'),
  ('cat_junior_meal_3_9', 'cat_junior', 9, '6:00 PM', 'feed', 'Meal #3', 'Feed after play — mirrors natural hunt → eat → groom → sleep cycle', '🍽️', 'Evening'),
  ('cat_junior_self_grooming_window_10', 'cat_junior', 10, '6:20 PM', 'groom', 'Self-Grooming Window', 'Cats groom after eating — give them quiet space', '😺', 'Evening'),
  ('cat_junior_evening_rest_11', 'cat_junior', 11, '7:00 PM', 'sleep', 'Evening Rest', 'Second wind likely around 10 PM — plan a short play session if needed', '🌙', 'Evening'),
  ('cat_adolescent_meal_1_1', 'cat_adolescent', 1, '7:00 AM', 'feed', 'Meal #1', 'Transition to adult cat food by 12 months', '🍽️', 'Morning'),
  ('cat_adolescent_morning_play_2', 'cat_adolescent', 2, '7:20 AM', 'play', 'Morning Play', '15–20 min — burn that adolescent energy before you start your day', '🪄', 'Morning'),
  ('cat_adolescent_rest_3', 'cat_adolescent', 3, '8:30 AM', 'sleep', 'Rest', 'They''ll find their own spot — window perches and cat trees earn their keep now', '💤', 'Morning'),
  ('cat_adolescent_enrichment_window_4', 'cat_adolescent', 4, '2:00 PM', 'enrich', 'Enrichment Window', 'Puzzle feeder, bird/squirrel videos, window watching — mental stimulation matters', '🧩', 'Afternoon'),
  ('cat_adolescent_play_session_5', 'cat_adolescent', 5, '3:00 PM', 'play', 'Play Session', 'Rotate toys to maintain novelty — cats bore quickly', '🪄', 'Afternoon'),
  ('cat_adolescent_grooming_6', 'cat_adolescent', 6, '4:00 PM', 'groom', 'Grooming', 'Brush, check ears, trim nails if needed', '🪮', 'Afternoon'),
  ('cat_adolescent_pre_dinner_play_7', 'cat_adolescent', 7, '6:00 PM', 'play', 'Pre-Dinner Play', 'Hunt → eat → groom → sleep is the natural cycle. Play before feeding.', '🪄', 'Evening'),
  ('cat_adolescent_meal_2_8', 'cat_adolescent', 8, '6:30 PM', 'feed', 'Meal #2', NULL, '🍽️', 'Evening'),
  ('cat_adolescent_rest_crepuscular_wind_up_9', 'cat_adolescent', 9, '7:30 PM', 'sleep', 'Rest / Crepuscular Wind-Up', 'Expect zoomies around dusk — totally normal, not a problem', '💤', 'Evening'),
  ('cat_adolescent_bedtime_play_session_10', 'cat_adolescent', 10, '9:30 PM', 'play', 'Bedtime Play Session', '10–15 min right before you sleep — dramatically reduces 3 AM wake-ups', '🪄', 'Evening'),
  ('cat_adolescent_night_11', 'cat_adolescent', 11, '10:00 PM', 'sleep', 'Night', 'Cat may still be active — this is their nature. Closed bedroom door is valid.', '🌙', 'Evening'),
  ('cat_adult_meal_1_1', 'cat_adult', 1, '7:00 AM', 'feed', 'Meal #1', 'Consistent timing helps regulate behavior and reduce wake-up yowling', '🍽️', 'Morning'),
  ('cat_adult_morning_play_2', 'cat_adult', 2, '7:20 AM', 'play', 'Morning Play', '10–15 min — wand toy, laser pointer, or chase', '🪄', 'Morning'),
  ('cat_adult_rest_3', 'cat_adult', 3, '8:00 AM', 'sleep', 'Rest', 'Adult cats sleep 12–16 hrs/day — that''s normal, not laziness', '💤', 'Morning'),
  ('cat_adult_enrichment_optional_4', 'cat_adult', 4, '12:00 PM', 'enrich', 'Enrichment (optional)', 'Puzzle feeder, window bird feeder view, a cardboard box — simple works', '🧩', 'Midday'),
  ('cat_adult_pre_dinner_play_5', 'cat_adult', 5, '5:30 PM', 'play', 'Pre-Dinner Play', '15–20 min — the most important interactive session of the day', '🪄', 'Afternoon / Evening'),
  ('cat_adult_meal_2_6', 'cat_adult', 6, '6:00 PM', 'feed', 'Meal #2', NULL, '🍽️', 'Afternoon / Evening'),
  ('cat_adult_grooming_7', 'cat_adult', 7, '6:20 PM', 'groom', 'Grooming', 'Short-haired: 2–3× week. Long-haired: daily. Check eyes, ears, teeth monthly.', '🪮', 'Afternoon / Evening'),
  ('cat_adult_evening_rest_8', 'cat_adult', 8, '7:00 PM', 'sleep', 'Evening Rest', NULL, '💤', 'Afternoon / Evening'),
  ('cat_adult_bedtime_play_9', 'cat_adult', 9, '9:30 PM', 'play', 'Bedtime Play', '10 min — reduces overnight disruptions significantly', '🪄', 'Afternoon / Evening'),
  ('cat_adult_night_10', 'cat_adult', 10, '10:00 PM', 'sleep', 'Night', NULL, '🌙', 'Afternoon / Evening'),
  ('cat_mature_meal_1_1', 'cat_mature', 1, '7:00 AM', 'feed', 'Meal #1', 'Consider transitioning to a mature/senior formula — ask your vet', '🍽️', 'Morning'),
  ('cat_mature_morning_play_2', 'cat_mature', 2, '7:20 AM', 'play', 'Morning Play', '10 min — gentler pace is fine, but keep it going. Mental engagement matters more now.', '🪄', 'Morning'),
  ('cat_mature_rest_3', 'cat_mature', 3, '8:00 AM', 'sleep', 'Rest', 'May sleep more than before — normal', '💤', 'Morning'),
  ('cat_mature_enrichment_4', 'cat_mature', 4, '12:00 PM', 'enrich', 'Enrichment', 'Food puzzles, bird window, calm interaction — low-effort, high-reward', '🧩', 'Midday'),
  ('cat_mature_play_before_dinner_5', 'cat_mature', 5, '5:30 PM', 'play', 'Play Before Dinner', 'Gentler toys — wand at slower pace, or a fishing rod toy they can bat from a lie-down', '🪄', 'Afternoon / Evening'),
  ('cat_mature_meal_2_6', 'cat_mature', 6, '6:00 PM', 'feed', 'Meal #2', NULL, '🍽️', 'Afternoon / Evening'),
  ('cat_mature_grooming_health_check_7', 'cat_mature', 7, '6:20 PM', 'groom', 'Grooming + Health Check', 'Feel for lumps, check coat quality, note any changes in weight or coat condition', '🪮', 'Afternoon / Evening'),
  ('cat_mature_night_8', 'cat_mature', 8, '9:30 PM', 'sleep', 'Night', NULL, '🌙', 'Afternoon / Evening'),
  ('cat_senior_meal_1_1', 'cat_senior', 1, '7:00 AM', 'feed', 'Meal #1', 'May do better on 3 smaller meals. Warmed wet food is more aromatic and easier if appetite is low.', '🍽️', 'Morning'),
  ('cat_senior_gentle_interaction_2', 'cat_senior', 2, '7:20 AM', 'play', 'Gentle Interaction', '5–10 min — slow feather drag, or simply lap time. Don''t force activity.', '🪄', 'Morning'),
  ('cat_senior_rest_3', 'cat_senior', 3, '8:00 AM', 'sleep', 'Rest', 'May sleep 18–20 hrs/day — provide warm, accessible spots at floor level', '💤', 'Morning'),
  ('cat_senior_meal_2_if_3_day_4', 'cat_senior', 4, '12:00 PM', 'feed', 'Meal #2 (if 3×/day)', 'Monitor intake closely — appetite changes are the earliest sign of illness', '🍽️', 'Midday'),
  ('cat_senior_calm_enrichment_5', 'cat_senior', 5, '12:30 PM', 'enrich', 'Calm Enrichment', 'Bird feeder window, quiet company, gentle petting — presence is enrichment', '🧩', 'Midday'),
  ('cat_senior_short_gentle_play_6', 'cat_senior', 6, '5:30 PM', 'play', 'Short Gentle Play', 'A slow wand drag or batting a soft ball. Stop before they tire.', '🪄', 'Evening'),
  ('cat_senior_meal_2_or_3_7', 'cat_senior', 7, '6:00 PM', 'feed', 'Meal #2 or #3', NULL, '🍽️', 'Evening'),
  ('cat_senior_assisted_grooming_8', 'cat_senior', 8, '6:20 PM', 'groom', 'Assisted Grooming', 'Older cats may under-groom. Gentle daily brushing prevents mats and shows you coat/skin changes.', '🪮', 'Evening'),
  ('cat_senior_night_rest_9', 'cat_senior', 9, '8:00 PM', 'sleep', 'Night Rest', 'Nighttime confusion or yowling can signal cognitive dysfunction — mention it to your vet', '🌙', 'Evening');

ALTER TABLE schedule_tasks ALTER COLUMN plan_id SET NOT NULL;
ALTER TABLE completions ALTER COLUMN pet_id SET NOT NULL;
